Update scripts and add cron job

diff --git a/upgrade-iso b/upgrade-iso
--- a/upgrade-iso
+++ b/upgrade-iso
@@ -1,7 +1,7 @@
 #!/bin/bash
 ####################
 ### upgrade-iso ####
-version="0.7" ######
+version="0.8" ######
 ### JustBrowsing ###
 ####################
 
@@ -31,7 +31,7 @@ CLEAN_UP()
 
 
 # Autobuild support
-if [ -z "$1" ]; then
+if [ -z "$isoFile" ]; then
   latest=$(grep "Successfully built:" "${buildDir}/latest" 2>/dev/null | awk '{print $NF}');
   isoFile=$(readlink -e "$latest" 2>/dev/null);
 fi
@@ -164,7 +164,6 @@ chroot "$mntDir" mkinitcpio -p linux
 cp "${mntDir}/boot/vmlinuz-linux" "${tmpDir}/vmlinuz-linux"
 cp "${mntDir}/boot/initramfs-linux.img" "${tmpDir}/initramfs-linux.img"
 chroot "$mntDir" /opt/justbrowsing/cleanup >/dev/null;
-chroot "$mntDir" /opt/justbrowsing/cleanup2 2>/dev/null;
 chroot "$mntDir" df -h 2>/dev/null | grep /$;
 
 # Upgrade AUR
@@ -202,6 +201,8 @@ if [[ "$input" != [Nn] ]]; then
   "$squashImage" "${tmpDir}/squashfs-root/root-image.fs" "$mntDir" --noconfirm &&
   echo "==> Convert to ISO  :: $sfs2ISO" &&
   "$sfs2ISO" "$tmpDir" "${buildDir}/syslinux" --nightly | tee "${buildDir}/iso.log" &&
+  isoStatus="$?";
+  [ "$isoStatus" = "0" ] && cp "${buildDir}/iso.log" "${buildDir}/latest";
   echo "[DONE]";
 else
   CLEAN_UP; 
@@ -220,55 +221,47 @@ if [ "$buildOVA" = "true" ]; then
     modprobe vboxdrv
     echo "==> Convert to OVA :: $iso2OVA"
     "$iso2OVA" "$isoFile" | tee "${buildDir}/ova.log" &&
+    ovaStatus="$?";
+    [ "$ovaStatus" = "0" ] && cp "${buildDir}/ova.log" "${buildDir}/latest-ova";
     echo "[DONE]";
   fi
 fi
 
 # Upload
-read -t 5 -n 1 -p "==> Upload OVA (Y/n): " input
+read -t 5 -n 1 -p "==> Upload (Y/n): " input
 echo "";
 if [[ "$input" != [Nn] ]]; then
-  ovaFile=$(grep "Successfully built:" "${buildDir}/ova.log" | awk '{print $NF}');
+
+  ovaFile=$(grep "Successfully built:" "${buildDir}/ova.log" 2>/dev/null | awk '{print $NF}');
   if [ "$buildOVA" = "true" -a -f "$ovaFile" ]; then
-    echo "==> scp $ovaFile justbrowsing@frs.sourceforge.net:/home/frs/project/justbrowsing/Virtual/"
-    scp "$ovaFile" justbrowsing@frs.sourceforge.net:/home/frs/project/justbrowsing/Virtual/;
+    echo "==> rsync -avP -e ssh $ovaFile justbrowsing@frs.sourceforge.net:/home/frs/project/j/ju/justbrowsing/Virtual/"
+    rsync -avP -e ssh "$ovaFile" justbrowsing@frs.sourceforge.net:/home/frs/project/j/ju/justbrowsing/Virtual/;
     ovaStatus="$?";
     if [ "$ovaStatus" != "0" ]; then
-      scp "$ovaFile" justbrowsing@frs.sourceforge.net:/home/frs/project/justbrowsing/Virtual/;
+      rsync -avP -e ssh "$ovaFile" justbrowsing@frs.sourceforge.net:/home/frs/project/j/ju/justbrowsing/Virtual/;
       ovaStatus="$?";
     fi
-    if [ "$ovaStatus" = "0" ]; then
-      cp "${buildDir}/ova.log" "${buildDir}/latest-ova"
-    else
-      echo "==> OVA Upload failed"
-    fi
-  else
-    echo "==> Upload failed"
+    [ "$ovaStatus" = "0" ] || echo "==> OVA Upload failed";
   fi
-fi
 
-read -t 5 -n 1 -p "==> Upload ISO (Y/n): " input
-echo "";
-if [[ "$input" != [Nn] ]]; then
-  isoFile=$(grep "Successfully built:" "${buildDir}/iso.log" | awk '{print $NF}');
+  isoFile=$(grep "Successfully built:" "${buildDir}/iso.log" 2>/dev/null | awk '{print $NF}');
   if [ -f "$buildDir/README.md" -a -f "$isoFile" ]; then
-    echo "==> scp $isoFile justbrowsing@frs.sourceforge.net:/home/frs/project/justbrowsing/Nightlies/"
-    scp "$isoFile" justbrowsing@frs.sourceforge.net:/home/frs/project/justbrowsing/Nightlies/ &&
-    echo "==> scp $buildDir/README.md justbrowsing@frs.sourceforge.net:/home/frs/project/justbrowsing/Nightlies/"
-    scp "$buildDir/README.md" justbrowsing@frs.sourceforge.net:/home/frs/project/justbrowsing/Nightlies/;
+    echo "==> rsync -avP -e ssh $isoFile justbrowsing@frs.sourceforge.net:/home/frs/project/j/ju/justbrowsing/Nightlies/"
+    rsync -avP -e ssh "$isoFile" justbrowsing@frs.sourceforge.net:/home/frs/project/j/ju/justbrowsing/Nightlies/;
     isoStatus="$?";
     if [ "$isoStatus" != "0" ]; then
-      scp "$buildDir/README.md" justbrowsing@frs.sourceforge.net:/home/frs/project/justbrowsing/Nightlies/;
+      rsync -avP -e ssh "$isoFile" justbrowsing@frs.sourceforge.net:/home/frs/project/j/ju/justbrowsing/Nightlies/;
       isoStatus="$?";
     fi
     if [ "$isoStatus" = "0" ]; then
-      cp "${buildDir}/iso.log" "${buildDir}/latest"
+      sleep 60;
+      echo "==> rsync -avP -e ssh $buildDir/README.md justbrowsing@frs.sourceforge.net:/home/frs/project/j/ju/justbrowsing/Nightlies/"
+      rsync -avP -e ssh "$buildDir/README.md" justbrowsing@frs.sourceforge.net:/home/frs/project/j/ju/justbrowsing/Nightlies/;
     else
-      echo "==> ISO Upload failed"
+      echo "==> ISO Upload failed";
     fi
-  else
-    echo "==> Upload failed"
   fi
+
 fi
 
 ### END ###
